### ISSUE TITLE
起動した時に画面が一瞬ちらつくのをどうにかしたい。

### ISSUE THREAD

**Issue by osyo-manga** [osyo-manga/vital-over#107]
どうにかしたい。

#### ちらつく

* Ubuntu 14.04 Vim 7.4.691
* Windows Vim 7.4.475（環境A)

#### ちらつかない

* Windows Vim 7.3.1314
* Windows Vim 7.4.475（環境B)

**Comment by osyo-manga** [comment]
いい加減これをどうにかしたい

**Comment by haya14busa** [comment]
原因究明したさですね...

**Comment by osyo-manga** [comment]
これ、真面目に調べてみたんですが原因がやっとわかりました。
`:digraphs` をキャプチャしようとすると何故か画面が再描画されるようです。

#### 再現コード

```vim
" このコードを :so % すると一瞬画面がちらつく
function! s:capture(cmd)
	let verbose_save = &verbose
	let &verbose = 0
	try
		redir => result
		execute "silent!" a:cmd
		redir END
	finally
		let &verbose = verbose_save
	endtry
	return result
endfunction

call s:capture(":digraphs")
```

#### 対策

今のところ不明。
出力が多いのが原因かと思ったんですが、同じく出力が多い `:function` や `:map` では再現しませんでした。
とりあえず、消極的な解決方法としては `Modules.Digraphs` を `disconnect()` しておくぐらいでしょうか…。

**Comment by osyo-manga** [comment]
Windows Vim 7.3.1314 だとちらつかなかったみたいです。

**Comment by osyo-manga** [comment]
再現環境まとめました。Windows だと再現しないぽい感じです

**Comment by osyo-manga** [comment]
と、思ったら手元の Windows Vim 7.4.475 で再現してしまった…。

**Comment by haya14busa** [comment]
おおー原因究明めでたい :tada: ただ手元のlinuxではcui/guiともに上記のcaptureのコードでは再現しませんでした...

解決方法としてはこれも消極的ではありますが，起動時にcaptureするのではなく, `<C-k>`を押した時に初めてcaptureするのが筋がいいかなと思います

**Comment by haya14busa** [comment]
`:so %`では再現しませんが, vital-over使用時にちらついてるのは以前gvimでは再現してたのでPRしましたっ

**Comment by osyo-manga** [comment]
> ただ手元のlinuxではcui/guiともに上記のcaptureのコードでは再現しませんでした...
> :so %では再現しませんが, 

むむむ…。上記の再現スクリプトだとまだ不十分なのかな…。
とりあえず、解決はしたぽいので閉じます。
ありがとうございました。

**Comment by haya14busa** [comment]
解決便利 :tada:
