### ISSUE TITLE
Modules/Doautocmd 時に現在のコマンドラインオブジェクトが参照できる仕組みがほしい

### ISSUE THREAD

**Issue by osyo-manga** [osyo-manga/vital-over#118]

**Comment by osyo-manga** [comment]
実装した

```vim

call vital#of("vital").unload()
let s:Doautocmd = vital#of("vital").import("Over.Commandline.Modules.Doautocmd")

function! s:func()
	let cmdline = s:Doautocmd.get_cmdline()
	if cmdline.is_input("a")
		call cmdline.setchar("b")
	endif
endfunction

augroup test
	autocmd!
	autocmd User OverCmdLineCharPre call s:func()
augroup END
```

**Comment by haya14busa** [comment]
はやさ++

`s:Doautocmd.get_cmdline()` を呼ぶ関数名をvital-overつかうﾌﾟﾗｷﾞﾝでなるべく統一しておくと便利そう

**Comment by osyo-manga** [comment]
テストも追加ed
時間があるときにでも incsearch.vim にとりこんでうれしい

**Comment by haya14busa** [comment]
- `plugin#cmdline`
- `plugin#cli`

あたりが短くてよさそうですかねー.

**Comment by osyo-manga** [comment]
んーとりあえず、vital-over だけ更新してもらえればこっちは問題ないですかね。

**Comment by haya14busa** [comment]
でも `s:DoAutocmd` 参照できなきゃ意味ないのでゎ?

**Comment by haya14busa** [comment]
あーもしや`vital#of`の値をプラギン名にすれば行けるのか

**Comment by osyo-manga** [comment]
それは

```
let s:Doautocmd = vital#of("incsearch").import("Over.Commandline.Modules.Doautocmd")
```

すればよいので問題ないですね

**Comment by haya14busa** [comment]
さすがにvital#of変えても無理だった

**Comment by osyo-manga** [comment]
上のコードで参照できませんでした？

**Comment by haya14busa** [comment]
あーなるほどできました. が, `s:cmdline`が定義されてないとでた

**Comment by osyo-manga** [comment]
んー vitalize した後にVimを再起動してもダメでした？

**Comment by haya14busa** [comment]
んーだめですね.

**Comment by osyo-manga** [comment]
こっち（over.vim）は問題なく動作しているんですがなんでだろう。

**Comment by haya14busa** [comment]
over.vimでも同様ですね.

```
vital-over:function <SNR>408_func..<SNR>410_get_cmdline, line 1 Vim(return):E121: Undefined variable: s:cmdline
```

しかし確かにコードみた限りでは行けるハズな気も...

**Comment by osyo-manga** [comment]
あーいや over.vim はまだ push してないです。
いま push しました。

**Comment by osyo-manga** [comment]
んーそれでもエラーメッセージがおかしいな

**Comment by haya14busa** [comment]
言われてみればover.vimが動いてなかったのは当たり前でしたねすいません

**Comment by haya14busa** [comment]
しかしupdateしても結果は同じであった

**Comment by haya14busa** [comment]
エラーの`vital-over`は https://github.com/osyo-manga/vim-over/blob/af9e411aaec30a5317795bfcdee0400eed5ff66c/autoload/over/command_line.vim#L27 でprefix指定してないからっぽいですね(そこはいま問題じゃないかもですが)

**Comment by osyo-manga** [comment]
ん、そこって関係あります？

**Comment by osyo-manga** [comment]
ああ、そういうことか

**Comment by osyo-manga** [comment]
再現するコード教えてもらえますか。

**Comment by osyo-manga** [comment]
あと関係ないかも知れませんが vital.vim は最新版ですか？

**Comment by haya14busa** [comment]
再現するコード, 全く同じなんですよね...あえて言うならIncSearchCharPreも足してる

```vim
call vital#of("vital").unload()
let s:Doautocmd = vital#of("vital").import("Over.Commandline.Modules.Doautocmd")

function! s:func()
    let cmdline = s:Doautocmd.get_cmdline()
    if cmdline.is_input("a")
        call cmdline.setchar("b")
    endif
endfunction

augroup test
    autocmd!
    autocmd User OverCmdLineCharPre call s:func()
    autocmd User IncSearchCharPre call s:func()
augroup END
```

**Comment by haya14busa** [comment]
vitalは最新です

**Comment by osyo-manga** [comment]
```vim
let s:Doautocmd = vital#of("vital").import("Over.Commandline.Modules.Doautocmd")
```
ではなくて
```vim
let s:Doautocmd = vital#of("over").import("Over.Commandline.Modules.Doautocmd")
```

が正しいです。

**Comment by haya14busa** [comment]
ｱ...そりゃそうですよね...アタマが働いてなかった...ありがとうございます

**Comment by osyo-manga** [comment]
はい

**Comment by haya14busa** [comment]
めっちゃ動作しましたっ!!!!!

**Comment by osyo-manga** [comment]
便利

**Comment by haya14busa** [comment]
便利. しかしこれdebug用という位置づけですかね.

**Comment by osyo-manga** [comment]
いえ、一応そういう機能として実装しました。

**Comment by haya14busa** [comment]
流石にめんどいと思うのでこんな感じでショートカット用意してもよさです?

```vim
function! incsearch#cli()
    return s:Doautocmd.get_cmdline()
endfunction
```

**Comment by osyo-manga** [comment]
それ自体はお任せします（と、いうかそれなら return s:cli でよいという気もします

**Comment by haya14busa** [comment]
incsearch.vim でdevブランチにはとりあえずｺﾐｯﾖしましたっ https://github.com/haya14busa/incsearch.vim/tree/dev

**Comment by osyo-manga** [comment]
ありがとうございますっ

**Comment by haya14busa** [comment]
> それ自体はお任せします（と、いうかそれなら return s:cli でよいという気もします

vital-over統一インターフェース的な意味で.
`s:cli`返すのは, もしかしたら複数objectを持ってる場合とかに`Doautocmd`参照だと対応できるという文脈なのかなぁと思ってた

**Comment by osyo-manga** [comment]
hm

**Comment by haya14busa** [comment]
とりあえず `incsearch#cli()` も定義しておいた

**Comment by haya14busa** [comment]
あーでもそうやって`Doautocmd`関係ない文脈にAPIを置くと取得できない問題が発生するか...

**Comment by haya14busa** [comment]
これ, 変なタイミングで呼んだ時にundefined variableみたいなエラーを返すのではなく, vital-overのエラーを返してもらえると嬉しい感あります

**Comment by osyo-manga** [comment]
> これ, 変なタイミングで呼んだ時にundefined variableみたいなエラーを返すのではなく, vital-overのエラーを返してもらえると嬉しい感あります

具体的にはどんな風を想定されていますか？（『vital-overのエラーを返す』というのがよくわからなかった

**Comment by haya14busa** [comment]
vital-overのエラーとしてキャッチするためには、このままだと無理だなという意味です。

vital-over prefixの適切なエラーメッセージをthrowしてほしい

**Comment by osyo-manga** [comment]
雑に追加してみました。

**Comment by haya14busa** [comment]
ありがとうございますっ

**Comment by haya14busa** [comment]
いまさら試しましたがなんでこれ, prefixこんな感じになってるんでしょう??? `_pluginname` みたいになってフレンドリー感なさそう https://github.com/osyo-manga/vital-over/blob/master/autoload/vital/__latest__/Over/Exception.vim#L6-L7

特に変える必要性なければ ExceptionMessage と同じ感じで投げて欲しいです https://github.com/osyo-manga/vital-over/blob/master/autoload/vital/__latest__/Over/Commandline/Modules/ExceptionMessage.vim の仕様と

**Comment by haya14busa** [comment]
あと仮にこのまま行くとして `==` のprefixは信用していいんでしょうか? つまり仕様変更とかにならないか気になります.

**Comment by osyo-manga** [comment]
出力フォーマットは雑に決めたので今後変更する可能性がないとは言えません。
もっとよい出力フォーマット案があればそっちに変更してもよいですが。

**Comment by osyo-manga** [comment]
別の issues 立てました。

**Comment by osyo-manga** [comment]
ちなみに `==` を prefix とした理由は単に強調したかっただけです。

**Comment by osyo-manga** [comment]
ああ、1つ前のコメント気づかなかった…。

> いまさら試しましたがなんでこれ, prefixこんな感じになってるんでしょう??? _pluginname みたいになってフレンドリー感なさそう

これの意図としては `_` の除いたほうがよいということでしょうか？
単にどのプラグイン（ディレクトリパス）から例外が発生したのかわかればよいと思ったのでディレクトリ名をそのまま出力するようにしています。

> 特に変える必要性なければ ExceptionMessage と同じ感じで投げて欲しいです 

ExceptionMessages は『例外を投げる』のではなくて『例外をハンドリングする』手段なので今回の話とはちょっと違うと思います。

**Comment by osyo-manga** [comment]
ちょっとわたしが勘違いしている知れませんが @haya14busa さんの意図としては、

* 例外を throw するときに出力フォーマットを統一してほしい
* `ExceptionMessages` で内部で例外が発生した際に出力されるフォーマットを統一してほしい

のどちらなのでしょうか。
わたしは throw するときのフォーマットの話かと思っているのですが。
