### ISSUE TITLE
vital-over 内での例外ハンドリングを考える

### ISSUE THREAD

**Issue by osyo-manga** [osyo-manga/vital-over#123]
ちょっと内容を変更しました。
出力フォーマットに限らず広い意味での例外処理（例外を排出するときや例外が発生した場合）をどうするかを考えます。
<del>出力フォーマット等必要であるのであれば仕様を決めたいと思います。</del>
#118

**Comment by haya14busa** [comment]
> 出力フォーマットは雑に決めたので今後変更する可能性がないとは言えません。
> もっとよい出力フォーマット案があればそっちに変更してもよいですが。

前issueでも書きましたが, `ExceptionMessage` の仕様でいいんじゃないかと思うのですがどうでしょう. 仮に変えるとしたら`ExceptionMessage` も統一して変えて欲しいです

**Comment by osyo-manga** [comment]
しまった、前の issues に返事したけどこっちに返事すればよかった。

**Comment by osyo-manga** [comment]
転載

> ああ、1つ前のコメント気づかなかった…。

>> いまさら試しましたがなんでこれ, prefixこんな感じになってるんでしょう??? _pluginname みたいになってフレンドリー感なさそう

> これの意図としては `_` の除いたほうがよいということでしょうか？
単にどのプラグイン（ディレクトリパス）から例外が発生したのかわかればよいと思ったのでディレクトリ名をそのまま出力するようにしています。

>> 特に変える必要性なければ ExceptionMessage と同じ感じで投げて欲しいです 

> ExceptionMessages は『例外を投げる』のではなくて『例外をハンドリングする』手段なので今回の話とはちょっと違うと思います。

**Comment by haya14busa** [comment]
> ExceptionMessages は『例外を投げる』のではなくて『例外をハンドリングする』手段なので今回の話とはちょっと違うと思います。

`ExceptionMessages` で実装しろと言っているわけではなく, 例外を投げるメッセージを統一して欲しいという意味です. 中身でやってることは違っても例外の投げ方は統一されていておかしくないのではと思います. 例えば本家vitalはちゃんと統一されてます

**Comment by osyo-manga** [comment]
> ExceptionMessages で実装しろと言っているわけではなく, 例外を投げるメッセージを統一して欲しいという意味です.

ExceptionMessages は例外を投げないんですがそういうことではなくて？
（`throw` とかエラー出力(`:echom`)とか関係なく）単純に『エラーメッセージを統一してほしい』、という話なのであればわかるんですが…。

**Comment by haya14busa** [comment]
> わたしは throw するときのフォーマットの話かと思っているのですが。
> https://github.com/osyo-manga/vital-over/issues/118#issuecomment-90556355

それであってます...と思ったらそもそも`ExceptionMessages`ってechoだったのか...(そういえば)
勘違いしてました

**Comment by haya14busa** [comment]
あれ, つまりこれって今のところvital-overって例外キャッチしてなんやかんやすることはできないのか

**Comment by osyo-manga** [comment]
> それであってます...と思ったらそもそもExceptionMessagesってechoだったのか...(そういえば)

ExceptionMessages は単純に『例外が発生した場合どうするかを決めるモジュール』なので `throw` はしてないですねぇ（ただ、make 時の command に `throw` は渡せそう

> あれ, つまりこれって今のところvital-overって例外キャッチしてなんやかんやすることはできないのか

ぶっちゃけ覚えてないのでちょっとコードみてきま

**Comment by osyo-manga** [comment]
これ、#118 の @haya14busa さんの意図としては、`ExceptionMessages` にいい感じの prefix を設定して、command を `throw` にすればよいような気もした

**Comment by osyo-manga** [comment]
そういえば、ExceptionMessages で throw したらどうなるのだろう

**Comment by haya14busa** [comment]
> （throw とかエラー出力(:echom)とか関係なく）単純に『エラーメッセージを統一してほしい』、という話なのであればわかるんですが…。

これ, 実際のところechoとthrowでメッセージ変えるのが一般的にどうなのかはわからないですが, 統一されててもよさそう

**Comment by osyo-manga** [comment]
> これ, 実際のところechoとthrowでメッセージ変えるのが一般的にどうなのかはわからないですが, 統一されててもよさそう

それはわかります。
ただ、`ExceptionMessages` は出力フォーマット変更できるようになっているのでちょっとむずかしそうな感じはしますねぇ…。

**Comment by haya14busa** [comment]
`vital-over(pluginname): エラーメッセージ` に変更して統一してもよさそう. `pluginname` の部分を変更できる感じで.

**Comment by osyo-manga** [comment]
内容ちょっと変えました。

**Comment by osyo-manga** [comment]
> vital-over(pluginname): エラーメッセージ に変更して統一してもよさそう. pluginname の部分を変更できる感じで.

ふーむ、ただ、`ExceptionMessages` で prefix を変更できるという利点として `hoge,vim: エラーメッセージ` みたいにもっとわかりやすく出力することもできるのがあるんですよねぇ。

**Comment by osyo-manga** [comment]
ただ、ExceptionMessages の prefix のデフォルト値が `vital-over(pluginname):` みたいな方がいいとは思いますね。

**Comment by haya14busa** [comment]
柔軟性は確かにありますが, `ExceptionMessages`ってvital-over関連から投げられた例外に限られるはずなので, vital-over 含めておく縛りしておくと, 原因わかりやすくてよさそう. 

ちょっと例外長くなるの他に, vital-over自体が悪くないのにvital-overがエラーメッセージに含まれていてよくわかってないプラギン使用者にとっての心象が悪くなるみたいなｱﾚもあったりするんだろうか.

**Comment by haya14busa** [comment]
> ただ、ExceptionMessages の prefix のデフォルト値が vital-over(pluginname): みたいな方がいい

+1

**Comment by osyo-manga** [comment]
> 柔軟性は確かにありますが, ExceptionMessagesってvital-over関連から投げられた例外に限られるはずなので, vital-over 含めておく縛りしておくと, 原因わかりやすくてよさそう.

これは製作者側からするとどこが原因なのかわかりやすいですが、利用者からみると `vital-over` と出力されてもわかりづらいという印象があります。

> プラギン使用者にとっての心象が悪くなるみたいなｱﾚもあったりするんだろうか.

そういうのは考えてないです。

**Comment by osyo-manga** [comment]
`vital-over(hoge):エラーメッセージ` と `hoge.vim:エラーメッセージ` を比較すると（利用者からみると）後者の方がどこでエラーになっているのかわかりやすいんじゃないか、と。
あと `pluginname` と書かれていますが、これは必ずしも『プラグイン名』とは限らないので。

**Comment by osyo-manga** [comment]
なので個人的には `vital-over(pluginname)` を prefix のデフォルト値としておけばよいかなーという感じですね。
（ここまで ExceptionMessages の話。

**Comment by osyo-manga** [comment]
話し変わるんですが ExceptionMessages の command のデフォルト値を `echo` から `echom` に変更しようと思うんですが、弊害とかってあったりしますかね？
`echo` してもその後の操作で消えてしまうとわからないので `echom` のほうが確認しやすいかなーと。

**Comment by haya14busa** [comment]
それでよさそうですかね. 地味に関係ないけど現状何も設定してないと`vital-over`しかエラーに表示されず, どのプラグインに報告市にしにいけばいいかわからないっぽいのがついでに解決できるとよさそう

**Comment by haya14busa** [comment]
確かむしろ僕が`echom`にしてくれっていったらコマンドで変更できるようにしていただいた経緯だったと思うので僕はむしろechom派ですね

**Comment by osyo-manga** [comment]
了解です。
とりあえず、ExceptionMessages の prefix と command のデフォルト値は変更します。

**Comment by haya14busa** [comment]
関連issueあった https://github.com/osyo-manga/vital-over/issues/38

**Comment by haya14busa** [comment]
(echomにしてくれとかもしかしたら言ってないかもしれない...ｽｲﾏｾﾝ)

**Comment by osyo-manga** [comment]
歴史は繰り返される…

**Comment by haya14busa** [comment]
> とりあえず、ExceptionMessages の prefix と command のデフォルト値は変更します。

一応ですが, むしろ Exception もおねがいします

**Comment by osyo-manga** [comment]
> 一応ですが, むしろ Exception もおねがいします

== ですか？

**Comment by osyo-manga** [comment]
とりあえず、Exception の方も ExceptionMessages とデフォルトの出力フォーマットを統一しました。

```
vital-over(__latest__) Exception : test in hom
```

というような出力になります。

**Comment by osyo-manga** [comment]
現状これで問題なさそうなので閉じちゃいますね。

**Comment by haya14busa** [comment]
> : わすれっぽい.
> https://github.com/osyo-manga/vital-over/commit/6451aac4ad63883aa18e5f095855fadb8076fa3c#commitcomment-10603682

これ治ってないです

**Comment by osyo-manga** [comment]
`:` は `s:throw_cmd()` で付けています。
『prefix で `:` をつけるべきだ！』というのであれば少し考えます。
`s:throw_cmd()` で付けてて問題ないのであれば `ExceptionMessage` もそういう仕様にしたいと思います（統一感的に。

**Comment by haya14busa** [comment]
あー`s:thsrow_cmd` でつけてたのか. 特に理由ないなら`ExceptionMessage`も統一したほうがいいと思います

**Comment by osyo-manga** [comment]
`Over.Exception` の方に統一しました。

**Comment by haya14busa** [comment]
ありがとうございますー
