### ISSUE TITLE
KeyMapping: palette が意図せず`{}`を返してきたときに対応してない

### ISSUE THREAD

**Issue by haya14busa** [osyo-manga/vital-over#126]
ref: https://github.com/osyo-manga/vital-palette/issues/5

paletteのバグによって意図しない`{}`が返ってきてしまうケースがあり，この時`buffer`keyにアクセスしようとしてエラーになってしまいます．

解決方法としては

1. そもそも全てちゃんとした値が返ってくる前提なのでpaletteでちゃんと対応する
2. paletteを全面的に信用するのではなく, vital-over側で`{}`を弾いてやる

の2つが考えられるかなぁと思いますがおしょーさんどうおもいます?

**Comment by osyo-manga** [comment]
ありがとうございます。
とりあえず、palette 側で空の辞書を返さないように対応しました。

**Comment by haya14busa** [comment]
動作確認しました．対応ありがとうございました :tada:
