### ISSUE TITLE
Base オブジェクトの要素名の仕様を決める

### ISSUE THREAD

**Issue by osyo-manga** [osyo-manga/vital-over#128]
ユーザ側で Base オブジェクトを拡張したい場合に仕様が曖昧だったので決めたいと思います。

#### 問題点

ユーザ側で定義した要素が、将来的に Base オブジェクト側で定義される可能性がある。

```vim
let s:cmdline = s:Commandline.make_standard("Input:> ")
" もしかしたらすでに is_exit() が定義されているかもしれない
let s:cmdline.is_exit = 0
```

これを回避するために『○○○から始まる名前の要素は Base オブジェクトでは定義されない』みたいな仕様を決めたい。

#### Base オブジェクトが持つ要素の種類

Base オブジェクトで定義する要素は大まかにわけて以下のものがあると思います。

* 関数参照や変数（`s:base.start()` や `s:base.variables` など）
* ユーザ側から拡張される可能性のある関数（`on_leave()` など）

#### 案

次のような命名規則を決めようかと考えています。

* `_` + 英数字から始まる要素は Base オブジェクトで定義されないことを保証する
 * e.g. `_is_exit`
* 両端に `__` が付いてる、もしくは `on_` から始まる関数はユーザ側で拡張されることを想定している
 * `__execute__()` や `on_leave()`
* それ以外の名前をユーザ側で定義した場合に動作を保証しない

要約すると Base オブジェクト側で `_xxx` みたいな名前を使わないことを保証することで、ユーザ側は安全に変数を定義することができるという感じにしたいと考えています。
また、`__xxx__` みたいな関数は Base オブジェクトの処理を拡張したい事が結構あったので新しく追加しようかと考えています。

#### 新しい書き方のイメージ

```vim
let s:cmdline = s:Commandline.make_standard("/")

" ユーザ側で使いたい変数は _ からはじめる
let s:cmdline._hoge = 10
let s:cmdline._foo  = "bar"

" 実行時の処理を拡張する関数
function! s:cmdline.__execute__(command)
	execute "/" . a:command
endfunction

" 内部で __execute__ が呼ばれる
call s:cmdline.execute("search_word")

```

この仕様で問題なさそうであれば適当なタイミングで書き直したいと思います。

**Comment by haya14busa** [comment]
ふむふむ，見た感じは便利そうだしその仕様でよさ気だと思います．一瞬vital-over側で`_`始まりのヘルパー関数定義しずらくなるかなと思いましたが開発の仕方の問題っぽいですし問題なさそう

**Comment by osyo-manga** [comment]
> 一瞬vital-over側で_始まりのヘルパー関数定義しずらくなるかなと思いましたが開発の仕方の問題っぽいですし問題なさそう

そこはまぁ `__xxx` みたいな名前に変更するだけでよいかなーと思ってました。

**Comment by haya14busa** [comment]
> __xxx みたいな名前に変更する

...! なるほど力が高い(よく読めてませんでしたｽｲﾏｾﾝ)

何気に変数とか関数はプラグイン側でvital-over拡張したい場合とユーザ側でvimrcからなどで拡張したい場合の2つがあってそのへんも仕様として決まっていればコンフリクトよりしなくなりそうだけど，特にそれを解決できそうなよさ気な案はなかった(完)

**Comment by osyo-manga** [comment]
> 変数とか関数はプラグイン側でvital-over拡張したい場合とユーザ側でvimrcからなどで拡張したい場合の2つがあって

2段階で拡張を行ないたい場合難しいんですよねぇ…。
いい仕組みがあればとは思うんですが。

**Comment by osyo-manga** [comment]
ここまで考えた（完全にスレチ

```vim
let s:base = {}

function! s:base.__func__()
	echo "base"
endfunction

function! s:base.func()
	call self.__func__()
endfunction


function! s:make_base()
	let obj = deepcopy(s:base)
	let obj.super = deepcopy(s:base)
	return obj
endfunction


let s:A = s:make_base()

function! s:A.__func__()
	call self.super.__func__()
	echo "A.__func__"
endfunction

echo "---------------------------------"
call s:A.func()

function! s:make_A()
	let obj = deepcopy(s:A)
	let obj.super = deepcopy(s:A)
	return obj
endfunction


let s:B = s:make_A()

function! s:B.__func__()
	call self.super.__func__()
	echo "B.__func__"
endfunction

echo "---------------------------------"
call s:B.func()
```
```
---------------------------------
base
A.__func__
---------------------------------
base
A.__func__
B.__func__
```

**Comment by haya14busa** [comment]
`super`...! それをVim scriptでやる発想がなかった...うまくハマればかなり便利そげかもですね...!

**Comment by osyo-manga** [comment]
これですが、Base オブジェクトだけではなくて、モジュールにも適用させようと思います。

**Comment by osyo-manga** [comment]
branch/issues_128 にて `_xxx` から `__xxx` への変更を行ないました。
問題がなければ master にﾏｯｼﾞしたいと思います。

**Comment by haya14busa** [comment]
遅くなってすいません. `issue_128` をincsearch.vimに組みこんでテストしてみましたがオールオッケーでした．diffも軽くみましたが大丈夫そうです

**Comment by haya14busa** [comment]
あえて言うならこの仕様を, ユーザ定義だけでなくvital-overの内部実装も含めコメントかドキュメントかどこかに書いてある or このissueへのリンクくらいがあると，あとになってもわかりやすいかつ，ｺﾝﾄﾘﾋﾞｭｯｼｮﾝしたいヒトが現れてもわかりやすいかなぁと思いました

**Comment by osyo-manga** [comment]
> 遅くなってすいません. issue_128 をincsearch.vimに組みこんでテストしてみましたがオールオッケーでした．diffも軽くみましたが大丈夫そうです

ありがとうございます。あとでマージします。

> あえて言うならこの仕様を, ユーザ定義だけでなくvital-overの内部実装も含めコメントかドキュメントかどこかに書いてある 

んー一応 doc には『普通に呼び出す関数（`xxx()`）』『コールバック関数（`on_xxx()`）』『ユーザ側で拡張できる関数（`__xxx__`）』みたいな分類別に書いておけばよいかなーと思っています。
まぁ簡単に書いてあってもよさそうですね。

**Comment by osyo-manga** [comment]
master にﾏｯｼﾞしました。

> あえて言うならこの仕様を, ユーザ定義だけでなくvital-overの内部実装も含めコメントかドキュメントかどこかに書いてある or このissueへのリンクくらいがあると，

doc にリンクを追加しておきました。

**Comment by haya14busa** [comment]
ありがとうございます．また試して何かあったら報告します
